# site settings
title: Juliano Labs
subtitle: powered by Curiosity
email: oliveira.juliano@outlook.com
description: Estudos, experimentações e exemplos gerados nessa caminhada em busca de conhecimento.(que descrição mais piegas)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://julianoengineer.github.io" # the base hostname & protocol for your site
author: Juliano Oliveira
#street_address: 
city: São Paulo
state: SP
#zip_code: 55555
country: Brazil
#phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/JulianoEngineer
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/julianoalvesoliveira/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/JulianoEngineer

# build settings
markdown: kramdown

sass:
  style: compressed
